### ISSUE TITLE
extra-bindings has gone

### ISSUE THREAD

**Issue by nobuto-m** [canonical/openstack-exporter-operator#90]
Assuming this charm is a rewrite of https://charmhub.io/prometheus-openstack-exporter, the previously supported `extra-bindings` (https://git.launchpad.net/charm-prometheus-openstack-exporter/tree/src/metadata.yaml#n30) has gone without any commit history.

There were reasons to have such metadata especially this charm handles OpenStack with admin/internal/public endpoints.

This is a blocker to use the new charm since it doesn't cover the existing deployment scenarios, i.e. complex enterprise networking where a routing from admin network to public network is not allowed.

**Comment by nobuto-m** [comment]
This is an expected bundle when extra-bindings are supported. This means that a created LXD container will have legs to each network including OAM (to forward logs and metrics to COS), internal network to fetch the keystone credentials over a relation, and public network to poke the OpenStack API endpoint. Otherwise, the underlying network requires some special routing to allow traffic from OAM to the public network, which is unlikely to be done in enterprise env.

```
  openstack-exporter:
    bindings:
      ? ''
      : oam-space
      cos-agent: oam-space
      credentials: internal-space
      public: public-space
    charm: openstack-exporter
    num_units: 1
    series: jammy
    to:
    - lxd:3
```
